id: A95C0F4CB
title: Homage to Milarepa
type: translation
pechas:
- I694A885F
- I5EC96BA2
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:02:17.548846
  last_modified_at: 2023-01-04 13:02:17.548856
  collections:
  - Milarepa Series
  - Works of Tibetan Masters
alignment_to_base:
  I694A885F/BB8C: A071
  I5EC96BA2/168E: A071
